### ISSUE TITLE
Update README for even more clarity.

### ISSUE THREAD

**Issue by jurassicplayer** [ajd4096/inject_gba#2]
You could also maybe include that it requires Python3 and PyYaml...among various other lesser issues that pedro had (trying to run the unpack-psb.py script from the main folder, trying to pass off directories as files, etc).

**Comment by ajd4096** [comment]
The shebang line exists for a reason. Learn to use it.

It is impossible for me to know which modules your system installs by default.
I'm not going to list them all; if it complains about a missing import, install it.

I run it from the main folder all the time, no idea what you mean by the rest.

**Comment by ajd4096** [comment]
setup tools + complete instructions for installing on Centos6, I'll add more mañana.
518 added a short entry to "the definitive guide"
